### ISSUE TITLE
checklist of visualizations to add

### ISSUE THREAD

**Issue by taylorreiter** [Arcadia-Science/2022-prjna853785-sourmash#2]
+ [x] creating a bar chart colored by superkingdom to get an overall breakdown of how much of a sample was identified for a given kingdom. this will also include an “unidentified” gray fraction.
+ [ ] potentially making the taxonomy plots interactive. if we hover over a phylum-level plot, can we see all of the lineages included in that plot? (this might not work but i’ll try!)
+ [x] for the taxonomy upset plot, color the intersections by superkingdom.
+ [x] for the taxonomy upset plot, pul out the upset intersections and give users a way to look at them
+ [x] we really care about species/strains! so figure out a visualization that lets us dig into that…maybe for every genus that is present above 1% in samples, make a plot showing all species or all strains observed for that genus.
+ [x] metacoder plot
+ [ ] superkingdom specific notebooks. We care about different things for bacteria and viruses, so separate these out.
for the virus specific notebook (and maybe fungi too), we care about things like genome sizes and stuff. try and include this information if possible.
